### ISSUE TITLE
High temperature bug?

### ISSUE THREAD

**Issue by akx** [akx/sensirion-ble#6]
> The Sensiron integration reads values under 100F fine, but I have several SHD4x gadgets on latest 3.2 firmware, and when the temperature is high HA displays the value as negative. For example, the app reads 117.1F while HA reads -198.31F. Something is going on with how the integration is displaying/converting temperatures. Switching HA to C results in the display reading -127C. Seems to be an issue with a poorly handled variable somewhere.

_Originally posted by @digitalentropy in https://github.com/home-assistant/core/issues/93678#issuecomment-1694522112_

**Comment by digitalentropy** [comment]
Thank you for splitting off the bug. I narrowed down the inflection point to about 108.5F.

Here’s a fun graph with the example.

![image](https://github.com/akx/sensirion-ble/assets/1412286/c35933fe-edf0-4c6f-945a-8f890cc5f770)


I did also test the passive-ble-monitor HACS integration and that did not appear to have any issues displaying the correct temperature.

**Comment by freemanix** [comment]
This is similar to bug in parsing humidity in Sensirion MyCO2.

I think the problem is in using `struct.unpack("<hhh")` instead of correct unsigned` struct.unpack("<HHH")` in conversion functions.

**Comment by akx** [comment]
Yeah, it's probably signedness. There's a release-candidate version up now, can you try `pip install --pre sensirion-ble==0.1.1rc0` in your HA virtualenvs?

**Comment by freemanix** [comment]
Hi,

I was trying, but I run dockerized homeassistant, plus it version-pins all
components and reinstalls older version upon start.

But I tried to edit the sensirion_ble installation source and replaced the
"<hhh" with "<HHH" and after restart it finally shows humidity above 50%.

**Comment by akx** [comment]
@freemanix Thanks for verifying. HA PR: https://github.com/home-assistant/core/pull/100271
